version: '3.7'
services:
  chatterbox:
    build: ../server
    volumes:
      - ../server:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js
    environment:
      REDIS_HOST: redis
      MYSQL_DATABASE: Benutzerdatenbank
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_HOSTNAME: mariadb
      PORT: 8087
    depends_on:
      - mariadb
      - redis
    deploy:
      replicas: 3


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: Benutzerdatenbank
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: mariadb

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
      - ./loadbalancer/default.conf:/etc/nginx/conf.d/default.conf
      - ../server/public:/usr/share/nginx/html:ro
    depends_on:
      - chatterbox

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    volumes:
     - /mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

volumes:
  mariadb_data:
    driver: local
  mongo_data:
    driver: local
