version: '3.3'
services:
  app1:
    build: ../server
    volumes:
      - ../server:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js
    environment:
      MYSQL_DATABASE: Benutzerdatenbank
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_HOSTNAME: mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: Benutzerdatenbank
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: mariadb

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
      - ./loadbalancer/default.conf:/etc/nginx/conf.d/default.conf
      - ../server/public:/usr/share/nginx/html:ro
    depends_on:
      - app1

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mariadb_data:
