version: '3.3'
services:
  server:
    build: server
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_HOSTNAME: meinecooledb
    links:
      - meinecooledb
    depends_on:
      - meinecooledb
    command: nodemon -L server.js   #muss am ende gelöscht werden!!!!!!!!!!!
    volumes:
      - ./server:/usr/src/app:Z
  meinecooledb:
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: meinecooledb

  web:  
    image: nginx
    volumes:
      - ./loadbalancer:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
