version: '3.3'
services:
  server:
    build: server
    #ports:
     # - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_HOSTNAME: meinecooledb
    links:
      - meinecooledb
    depends_on:
      - meinecooledb
    # Overwrite to nodemon only for DEV! -L is legacy mode, required for Windows / Mac integration.
    command: nodemon -L server.js
    # Host mount path overwrite for nodemon - only for DEV!
    volumes:
      # :Z may needs to be removed, if this does not work
      - ./server:/usr/src/app:Z
  meinecooledb:
    # Use of a modified datbase in 'db'-folder.
    # See README.md for more information.
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: meinecooledb

      web:
  image: nginx
  volumes:
   - ./loadbalancer:/etc/nginx/templates
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80

     mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
